# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9751c440740d3809db4ee1d3829d1e0d4b3e5f286181909cc567c2c2a385a16d21e68dcc1ef90110e8c01001624413a72f63d95f40f4e85c8c13a02026d661e

test:
  secret_key_base: b82dd28db7159573ff55d3381525a8b5919cfff7e9ae70e7c38a8fab0ef02d4bb9bcef0aecc359df6d5ae6cc7c10146e2285ec8bf252379720287edc398edbcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
